
service: alerts-cloudwatch
frameworkVersion: '2.72.3'

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iam:
    role:
      name: actual
      statements:
      - Effect: Allow
        Action: sns:Publish
        Resource: arn:aws:sns:us-east-1:083868342691:errors
      - Effect: Allow
        Action: '*'
        Resource: arn:aws:logs:us-east-1:083868342691:log-group:/aws/lambda/checking-test:*
      - Effect: Allow
        Action: '*'
        Resource: arn:aws:lambda:us-east-1:083868342691:function:error-log
      - Effect: Allow
        Action: '*'
        Resource: arn:aws:logs:us-east-1:083868342691:log-group:/aws/lambda/checking-test:*
      
      
functions:
  lambda_handler:
    handler: handler.lambda_handler
    name: error-log
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/checking-test'
          filter: '?ERROR ?WARN ?5xx'
    environment:
      ACCOUNT_ID: 083868342691
      snsARN: arn:aws:sns:us-east-1:083868342691:errors


resources:
   Resources:
     snsTopic: 
       Type: AWS::SNS::Topic
       Properties:
         TopicName: errors
     MySnsSubscription:
       Type: AWS::SNS::Subscription
       Properties:
         Endpoint: sahith.palika@bizcloudexperts.com
         Protocol: email
         TopicArn: !Ref snsTopic
