service: alerts-cloudwatch
frameworkVersion: '2.72.3'

custom:
  accountId:  AWS::AccountId
  namesns: errors
  lambda: error-log
  log: '/aws/lambda/checking-test'

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iam:
    role:
      name: actual
      statements:
      - Effect: Allow
        Action: sns:Publish
        Resource: !Sub 'arn:aws:sns:us-east-1:${AWS::AccountId}:${self:custom.namesns}'
      - Effect: Allow
        Action: '*'
        Resource: !Sub 'arn:aws:lambda:us-east-1:${AWS::AccountId}:function:${self:custom.lambda}'
      - Effect: Allow
        Action: '*'
        Resource: !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:${self:custom.log}:*'
      
      
functions:
  lambda_handler:
    handler: handler.lambda_handler
    name: ${self:custom.lambda}
    events:
      - cloudwatchLog:
          logGroup: ${self:custom.log}
          filter: '?ERROR ?WARN ?5xx'
    environment:
      ACCOUNT_ID: ${AWS::AccountId}
      snsARN: Sub! 'arn:aws:sns:us-east-1:${AWS::AccountId}:${self:custom.namesns}'


resources:
   Resources:
     snsTopic: 
       Type: AWS::SNS::Topic
       Properties:
         TopicName: ${self:custom.namesns}
     MySnsSubscription:
       Type: AWS::SNS::Subscription
       Properties:
         Endpoint: sahith.palika@bizcloudexperts.com
         Protocol: email
         TopicArn: !Ref snsTopic

